### ISSUE TITLE
On P&E dashboard, database errors are occuring during pageview import

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#1134]
Two different stack traces:

```
ActiveRecord::ActiveRecordError: Cannot lease connection, it is already in use by a different thread: #<Thread:0x00000009345d60>. Current thread: #<Thread:0x00000006a851a0>.
  from lib/importers/view_importer.rb:48:in `block (2 levels) in update_views_for_articles_batch'
  from lib/importers/view_importer.rb:60:in `fetch_views_in_thread'
  from lib/importers/view_importer.rb:60:in `new'
  from lib/wiki_pageviews.rb:8:in `initialize'
  from active_record/associations/builder/association.rb:111:in `wiki'
  from active_record/associations/singular_association.rb:15:in `reader'
  from active_record/associations/association.rb:53:in `reload'
  from active_record/associations/association.rb:138:in `load_target'
  from active_record/associations/singular_association.rb:63:in `find_target'
  from active_record/associations/singular_association.rb:48:in `get_records'
  from active_record/associations/association.rb:261:in `skip_statement_cache?'
  from active_record/associations/association.rb:86:in `scope'
  from active_record/associations/association.rb:97:in `association_scope'
  from active_record/connection_handling.rb:91:in `connection'
  from active_record/connection_handling.rb:128:in `retrieve_connection'
  from active_record/connection_adapters/abstract/connection_pool.rb:875:in `retrieve_connection'
  from active_record/connection_adapters/abstract/connection_pool.rb:364:in `connection'
  from active_record/connection_adapters/abstract/connection_pool.rb:501:in `checkout'
  from active_record/connection_adapters/abstract/connection_pool.rb:705:in `acquire_connection'
  from active_record/connection_adapters/abstract/connection_pool.rb:148:in `poll'
  from active_record/connection_adapters/abstract/connection_pool.rb:158:in `synchronize'
  from monitor.rb:214:in `mon_synchronize'
  from active_record/connection_adapters/abstract/connection_pool.rb:148:in `block in poll'
  from active_record/connection_adapters/abstract/connection_pool.rb:279:in `internal_poll'
  from active_record/connection_adapters/abstract_adapter.rb:174:in `lease'
```

----

```
Mysql2::Error: Lost connection to MySQL server during query
  from lib/importers/view_importer.rb:48:in `block (2 levels) in update_views_for_articles_batch'
  from lib/importers/view_importer.rb:60:in `fetch_views_in_thread'
  from lib/importers/view_importer.rb:60:in `new'
  from lib/wiki_pageviews.rb:8:in `initialize'
  from active_record/associations/builder/association.rb:111:in `wiki'
  from active_record/associations/singular_association.rb:15:in `reader'
  from active_record/associations/association.rb:53:in `reload'
  from active_record/associations/association.rb:138:in `load_target'
  from active_record/associations/singular_association.rb:63:in `find_target'
  from active_record/associations/singular_association.rb:59:in `get_records'
  from active_record/statement_cache.rb:109:in `execute'
  from active_record/querying.rb:39:in `find_by_sql'
  from active_record/connection_adapters/mysql/database_statements.rb:10:in `select_all'
  from active_record/connection_adapters/abstract/query_cache.rb:70:in `select_all'
  from active_record/connection_adapters/abstract/database_statements.rb:41:in `select_all'
  from active_record/connection_adapters/abstract/database_statements.rb:373:in `select'
  from active_record/connection_adapters/mysql/database_statements.rb:51:in `exec_query'
  from active_record/connection_adapters/abstract_mysql_adapter.rb:225:in `execute_and_free'
  from active_record/connection_adapters/mysql/database_statements.rb:46:in `execute'
  from active_record/connection_adapters/abstract_mysql_adapter.rb:218:in `execute'
  from active_record/connection_adapters/abstract_adapter.rb:560:in `log'
  from active_support/notifications/instrumenter.rb:21:in `instrument'
  from active_record/connection_adapters/abstract_adapter.rb:566:in `block in log'
  from active_record/connection_adapters/abstract_mysql_adapter.rb:218:in `block in execute'
  from mysql2/client.rb:119:in `query'
  from mysql2/client.rb:119:in `handle_interrupt'
  from mysql2/client.rb:120:in `block in query'
  from mysql2/client.rb:120:in `_query'
```

**Comment by ragesoss** [comment]
Hopefully this is no longer an issue, since I think we removed the database queries within the threads for the view import process.
