### ISSUE TITLE
Replica queries by article title on Hebrew Wikipedia may fail because URI is too long

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#1264]
```
JSON::ParserError: 743: unexpected token at '<html>
<head><title>414 Request-URI Too Large</title></head>
<body bgcolor="white">
<center><h1>414 Request-URI Too Large</h1></center>
<hr><center>nginx/1.11.3</center>
</body>
</html>
'
  from lib/article_status_manager.rb:20:in `block (2 levels) in update_article_status'
  from lib/article_status_manager.rb:20:in `each'
  from lib/article_status_manager.rb:21:in `block (3 levels) in update_article_status'
  from lib/article_status_manager.rb:33:in `update_article_status_for_course'
  from active_record/relation/delegation.rb:38:in `each'
  from active_record/relation/delegation.rb:38:in `each'
  from lib/article_status_manager.rb:36:in `block in update_article_status_for_course'
  from lib/article_status_manager.rb:54:in `update_status'
  from lib/article_status_manager.rb:132:in `update_article_ids'
  from lib/utils.rb:9:in `chunk_requests'
  from lib/utils.rb:9:in `each'
  from lib/utils.rb:10:in `block in chunk_requests'
  from lib/article_status_manager.rb:133:in `block in update_article_ids'
  from lib/replica.rb:68:in `get_existing_articles_by_title'
  from lib/replica.rb:138:in `api_get'
  from json/common.rb:156:in `parse'
  from json/common.rb:156:in `parse'
```

This happens because we try to pass up to 100 titles at once to Replica, and if they are in a language where URI encoding significantly increases the number of characters — pretty much anything that is mostly not basic Latin characters — then the URI can grow much larger.

We can solve this by limiting the number of articles per request, as set in `ArticleStatusManager`. Ideally, we could move the chunking logic from `ArticleStatusManager#article_data_From_replica` directly into `Replica`, and have `Replica` handle breaking requests into multiple queries based on the URI length.

**Comment by ragesoss** [comment]
Still happening after changing it to 50 titles. I guess we should go with one of the more complicated solutions, either switching the value on language (easy, but not ideal) or moving the chunking into Replica and choosing number per query dynamically based on title length.
