### ISSUE TITLE
EOFError: end of file reached

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#1773]
This rare error should be handled gracefully like other common failures in WikiPageviews.

https://sentry2.wikiedu.org/wikiedu/p-e-dashboard/issues/1049/

```
EOFError: end of file reached
  lib/wiki_pageviews.rb:91:in `api_get'
    response = Net::HTTP::get(URI.parse(url))
  lib/wiki_pageviews.rb:72:in `fetch_view_data'
    data = api_get url
  lib/wiki_pageviews.rb:30:in `views_for_article'
    daily_view_data = fetch_view_data(start_date, end_date)
  lib/importers/view_importer.rb:63:in `fetch_views_in_thread'
    .new(article).views_for_article(start_date: since,
  lib/importers/view_importer.rb:51:in `block (2 levels) in update_views_for_articles_batch'
    fetch_views_in_thread(article, start)
...
(24 additional frame(s) were not displayed)

EOFError: end of file reached
```

**Comment by AmitJoki** [comment]
Um, is this the only change that's required? in the `rescue` block?
```
rescue EOFError, Errno::ETIMEDOUT, Errno::ENETUNREACH, SocketError
```

**Comment by ragesoss** [comment]
Yeah, I think so.
