### ISSUE TITLE
Data download options should include aggregate CSV of edits for a campaign

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#1877]
We have the option to download all the edits for a course, via the 'Download Stats' modal. A similar option for an entire campaign (like the others currently accessible from /campaigns) would be useful.

**Comment by robotscissors** [comment]
@ragesoss I am a new contributor, I would like to work on this.

I may have a few follow-up questions :)

**Comment by ragesoss** [comment]
@robotscissors cool! Ping here, ask on Slack, for any questions you have.

**Comment by robotscissors** [comment]
Hi @ragesoss,
Having trouble with the installation process. I am almost there, but need a nudge.

OS: Mac Sierra
I have installed on two separate machines.


Used two methods (manual and script)
- Succeeded in getting through mysql installation.
- Rails s - server starts nicely 
- localhost:3000 produces the following error:
No such file or directory @ rb_sysopen - /Users/christopher/work/bloc/wiki-dashboard/public/assets/stylesheets/rev-manifest.json
This error occurs when the asset build process has not generated the required rev-manifest.json files, which specify the filenames of the compiled stylesheet and javascript files.
Run `gulp` or `gulp build` and make sure there are no build errors.

**Running `gulp` or `gulp build` produces these errors:**
Let's go (~/work/bloc/wiki-dashboard$) > gulp build
[09:20:18] Failed to load external module @babel/register
[09:20:18] Failed to load external module babel-register
[09:20:18] Failed to load external module babel-core/register
[09:20:18] Failed to load external module babel/register
[09:20:18] Local gulp not found in ~/work/bloc/wiki-dashboard
[09:20:18] Try running: npm install gulp

Then, I burst in tears repeatedly.

**Comment by ragesoss** [comment]
@robotscissors try `npm install -g gulp` (or `sudo npm install -g gulp`), then re-run `gulp build`.

**Comment by robotscissors** [comment]
@ragesoss, I appreciate the attention.

`sudo npm install -g gulp` then `gulp build` 

Yielded this:

Let's go (~/work/bloc/wiki-dashboard$) > gulp build
[10:18:48] Failed to load external module @babel/register
[10:18:48] Failed to load external module babel-register
[10:18:48] Failed to load external module babel-core/register
[10:18:48] Failed to load external module babel/register
/Users/christopher/work/bloc/wiki-dashboard/gulpfile.babel.js:1
(function (exports, require, module, __filename, __dirname) { import gulp from 'gulp';
                                                                     ^^^

SyntaxError: Unexpected identifier
    at new Script (vm.js:74:7)
    at createScript (vm.js:246:10)
    at Object.runInThisContext (vm.js:298:10)
    at Module._compile (internal/modules/cjs/loader.js:670:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
    at Module.load (internal/modules/cjs/loader.js:612:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
    at Function.Module._load (internal/modules/cjs/loader.js:543:3)
    at Module.require (internal/modules/cjs/loader.js:650:17)
    at require (internal/modules/cjs/helpers.js:20:18)

<img width="617" alt="screen shot 2018-06-12 at 10 20 53 am" src="https://user-images.githubusercontent.com/24664863/41306243-5aae8eea-6e2a-11e8-9a82-b66b0ed214b3.png">

**Comment by ragesoss** [comment]
Hmmm.... haven't seen that before.

Did you get any error messages when you ran `yarn`?

Also, what version of nodejs are you using? (`node -v` or `nodejs -v`)

**Comment by robotscissors** [comment]
YOU were right! I needed to downgrade node. 
Node was at 10.X and I did `rvm use 9` and now I see the home page. Thank you!!

**Comment by robotscissors** [comment]
Hi @ragesoss, I plan on adding a link on the page below. Perhaps a link that says: Edit Statistics or All Edits?

Very well written application and I am still looking through it. Am I on the right track?

<img width="1070" alt="screen shot 2018-06-13 at 2 57 49 pm" src="https://user-images.githubusercontent.com/24664863/41380649-876c4346-6f1a-11e8-8636-ddcc313afce6.png">

**Comment by ragesoss** [comment]
Thank you!

Yep, that's the place for it for now. 'all edits' would be a good label.

At some point, we'll move all these links for each campaign to the `home` view for that campaign, and make `/campaigns` table use the same row layout as the `/explore` page, which shows stats for each campaign. But meanwhile, this is the place that makes sense.

**Comment by JiyaGupta-cs** [comment]
@ragesoss  It looks like we now have multiple options to download campaign stats as CSV. Do you think any further changes are needed?
