### ISSUE TITLE
Assignments do not load for some courses

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#190]
The Assignments section just says "loading" forever here: http://dashboard.wikiedu.org/courses/American_University/COMM535_%28Spring_2015%29/articles

This happens to be a class that has many assigned articles per student: https://en.wikipedia.org/wiki/Education_Program:American_University/COMM535_%28Spring_2015%29#Summary_and_students

**Comment by ragesoss** [comment]
Looks like this has an associated error from Sentry: http://sentry.ragesoss.com:8080/wiki-ed/production/group/243/

Stacktrace (most recent call first):
```
  app/views/courses/_assignments.json.jbuilder:4:in `block in _app_views_courses__assignments_json_jbuilder__90858330_92270270'
    json.user_wiki_id assignment.user.wiki_id
  jbuilder.rb:294:in `block (2 levels) in _map_collection'
    _scope{ yield element }
  jbuilder.rb:301:in `_scope'
    yield
  jbuilder.rb:294:in `block in _map_collection'
    _scope{ yield element }
  active_record/relation/delegation.rb:46:in `map'
    delegate :to_xml, :to_yaml, :length, :collect, :map, :each, :all?, :include?, :to_ary, :join, to: :to_a
  active_record/relation/delegation.rb:46:in `map'
    delegate :to_xml, :to_yaml, :length, :collect, :map, :each, :all?, :include?, :to_ary, :join, to: :to_a
  jbuilder.rb:293:in `_map_collection'
    collection.map do |element|
  jbuilder.rb:180:in `array!'
    _map_collection(collection, &block)
  jbuilder/jbuilder_template.rb:39:in `array!'
    super
  jbuilder.rb:31:in `block in set!'
    _scope{ array! value, &block }
  jbuilder.rb:301:in `_scope'
    yield
  jbuilder.rb:31:in `set!'
    _scope{ array! value, &block }
  action_dispatch/middleware/request_id.rb:21:in `call'
    @app.call(env).tap { |_status, headers, _body| headers["X-Request-Id"] = env["action_dispatch.request_id"] }
  rack/methodoverride.rb:21:in `call'
    @app.call(env)
  rack/runtime.rb:17:in `call'
    status, headers, body = @app.call(env)
  active_support/cache/strategy/local_cache_middleware.rb:26:in `call'
    response = @app.call(env)
  rack/sendfile.rb:112:in `call'
    status, headers, body = @app.call(env)
  raven/integrations/rack.rb:54:in `call'
    response = @app.call(env)
  rails/engine.rb:514:in `call'
    app.call(env)
  rails/application.rb:144:in `call'
    super(env)
  /usr/local/rvm/gems/ruby-2.1.5/gems/passenger-4.0.57/lib/phusion_passenger/rack/thread_handler_extension.rb:74:in `process_request'
    status, headers, body = @app.call(env)
  /usr/local/rvm/gems/ruby-2.1.5/gems/passenger-4.0.57/lib/phusion_passenger/request_handler/thread_handler.rb:141:in `accept_and_process_next_request'
    process_request(headers, connection, socket_wrapper, @protocol == :http)
  /usr/local/rvm/gems/ruby-2.1.5/gems/passenger-4.0.57/lib/phusion_passenger/request_handler/thread_handler.rb:109:in `main_loop'
    hijacked = accept_and_process_next_request(socket_wrapper, channel, buffer)
  /usr/local/rvm/gems/ruby-2.1.5/gems/passenger-4.0.57/lib/phusion_passenger/request_handler.rb:455:in `block (3 levels) in start_threads'
    handler.main_loop(set_initialization_state_to_true)
```

**Comment by ntdb** [comment]
The data base contains assignments with `user_id`s for nonexistent users. Will look for a cause shortly
