### ISSUE TITLE
NoMethodError when PlagiabotImporter query does not return results

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#2485]
https://sentry2.wikiedu.org/wikiedu/p-e-dashboard/issues/2602/

```
NoMethodError: undefined method `each' for nil:NilClass
  lib/importers/plagiabot_importer.rb:24:in `find_recent_plagiarism'
    suspected_diffs.each do |rev|
  lib/data_cycle/constant_update.rb:62:in `update_revisions_and_articles'
    PlagiabotImporter.find_recent_plagiarism
  lib/data_cycle/constant_update.rb:37:in `run_update'
    update_revisions_and_articles
  lib/data_cycle/batch_update_logging.rb:30:in `run_update_with_pid_files'
    run_update # implemented by each update class
  lib/data_cycle/constant_update.rb:30:in `initialize'
    run_update_with_pid_files(:constant)
...
(36 additional frame(s) were not displayed)

NoMethodError: undefined method `each' for nil:NilClass
```

**Comment by Aeropio** [comment]
Hello I am current outreachy applicant and wants to work on this issue, please know the steps to reproduce this in my local

**Comment by Aeropio** [comment]
@ragesoss : if we check `suspected_diffs.present?` then this mentioned error can be avoided; incase if `suspected_diffs` is not present then what the method has to return?

**Comment by ragesoss** [comment]
Something like that seems reasonable, although if there's anywhere earlier in the data flow to handle this failure mode, that would be better.

A patch for this should also include a test for a mocked query that would lead to this error.

**Comment by Aeropio** [comment]
@ragesoss in `api_get` method of **PlagiabotImporter** class if we check if response is present then it would be better, but if response is not present then what the method has to return?

**Comment by Aeropio** [comment]
> Something like that seems reasonable, although if there's anywhere earlier in the data flow to handle this failure mode, that would be better.
> 
> A patch for this should also include a test for a mocked query that would lead to this error.

@ragesoss  where should I write the test for the mocked query? in which file?

**Comment by ragesoss** [comment]
Probably plagiaibot_importer_spec.rb

**Comment by Aeropio** [comment]
@ragesoss : My understanding is that  `api_get` method returns nil in the `find_recent_plagiarism` method , but i am not sure how to reproduce this error?please share the  Steps to reproduce this behavior

**Comment by bwreid** [comment]
@Aeropio I think it will be easiest to just build the test so that the `Net::HTTP.get` returns `nil`. I think the problem at the moment is we're not entirely sure what yet is causing the return of `nil` but still want to be able to handle it.

**Comment by Aeropio** [comment]
@bwreid okay sure
