### ISSUE TITLE
Error for admins visiting /onboarding

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#2822]
https://sentry2.wikiedu.org/wikiedu/production/issues/2991/

```
TypeError: document.getElementById(...) is null
  at g (./app/assets/javascripts/components/nav/notifications_bell.jsx:11:20)
  at Vh (./node_modules/react-dom/cjs/react-dom.production.min.js:216:167)
  at Zh (./node_modules/react-dom/cjs/react-dom.production.min.js:220:182)
  at b (./node_modules/react-dom/cjs/react-dom.production.min.js:250:268)
  at r (./node_modules/scheduler/cjs/scheduler.production.min.js:18:156)
...
(18 additional frame(s) were not displayed)
```

**Comment by ragesoss** [comment]
Fixed.
