### ISSUE TITLE
Batch updates may get stuck indefinitely

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#288]
I think the servers must have gotten reset during updates last night, which means that the PID file for delaying updates didn't get cleaned up on both staging and production, and then no updates have happened since then.

Maybe we can use the PID file check whether the batch task is actually running, and delete it if not?

**Comment by ragesoss** [comment]
This has happened a couple of times in the last few weeks, resulting in a couple of days worth of no updates.

Seems to have been precipitated the most recent time by this error:

```
[2015-10-20 21:27:33.333 DEBUG] Finished updating cached values
rake aborted!
I18n::InvalidLocaleData: can not load translations from /var/www/dashboard/releases/20151020213947/config/locales/ar.yml: #<Errno
::ENOENT: No such file or directory @ rb_sysopen - /var/www/dashboard/releases/20151020213947/config/locales/ar.yml>
/var/www/dashboard/shared/bundle/ruby/2.1.0/gems/i18n-0.7.0/lib/i18n/backend/base.rb:184:in `rescue in load_yml'
/var/www/dashboard/shared/bundle/ruby/2.1.0/gems/i18n-0.7.0/lib/i18n/backend/base.rb:181:in `load_yml'
/var/www/dashboard/shared/bundle/ruby/2.1.0/gems/i18n-0.7.0/lib/i18n/backend/base.rb:165:in `load_file'
/var/www/dashboard/shared/bundle/ruby/2.1.0/gems/i18n-0.7.0/lib/i18n/backend/base.rb:15:in `block in load_translations'
/var/www/dashboard/shared/bundle/ruby/2.1.0/gems/i18n-0.7.0/lib/i18n/backend/base.rb:15:in `each'
/var/www/dashboard/shared/bundle/ruby/2.1.0/gems/i18n-0.7.0/lib/i18n/backend/base.rb:15:in `load_translations'
/var/www/dashboard/shared/bundle/ruby/2.1.0/gems/i18n-0.7.0/lib/i18n/backend/simple.rb:57:in `init_translations'
/var/www/dashboard/shared/bundle/ruby/2.1.0/gems/i18n-0.7.0/lib/i18n/backend/simple.rb:40:in `available_locales'
/var/www/dashboard/shared/bundle/ruby/2.1.0/gems/i18n-0.7.0/lib/i18n/config.rb:43:in `available_locales'
/var/www/dashboard/shared/bundle/ruby/2.1.0/gems/i18n-0.7.0/lib/i18n/config.rb:49:in `available_locales_set'
/var/www/dashboard/shared/bundle/ruby/2.1.0/gems/i18n-0.7.0/lib/i18n.rb:278:in `locale_available?'
/var/www/dashboard/shared/bundle/ruby/2.1.0/gems/i18n-0.7.0/lib/i18n.rb:284:in `enforce_available_locales!'
/var/www/dashboard/shared/bundle/ruby/2.1.0/gems/i18n-0.7.0/lib/i18n.rb:151:in `translate'
/var/www/dashboard/shared/bundle/ruby/2.1.0/gems/activesupport-4.1.8/lib/active_support/option_merger.rb:22:in `method_missing'
/var/www/dashboard/shared/bundle/ruby/2.1.0/gems/actionview-4.1.8/lib/action_view/helpers/date_helper.rb:95:in `block in distance
_of_time_in_words'
/var/www/dashboard/shared/bundle/ruby/2.1.0/gems/activesupport-4.1.8/lib/active_support/core_ext/object/with_options.rb:40:in `wi
th_options'
/var/www/dashboard/shared/bundle/ruby/2.1.0/gems/actionview-4.1.8/lib/action_view/helpers/date_helper.rb:78:in `distance_of_time_
in_words'
/var/www/dashboard/releases/20151020213947/lib/tasks/batch.rake:49:in `block (2 levels) in <top (required)>'
Errno::ENOENT: No such file or directory @ rb_sysopen - /var/www/dashboard/releases/20151020213947/config/locales/ar.yml
```
