### ISSUE TITLE
RSpec test fails with lack of sqlite3 gem

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#30]
I found this in my Guard console:

12:57:16 - INFO - Running: spec/models/article_spec.rb spec/models/user_spec.rb
/home/sage/.rvm/gems/ruby-2.1.5/gems/activerecord-4.1.8/lib/active_record/connection_adapters/connection_specification.rb:190:in `rescue in spec': Specified 'sqlite3' for database adapter, but the gem is not loaded. Add `gem 'sqlite3'` to your Gemfile (and ensure its version is at the minimum required by ActiveRecord). (Gem::LoadError)
	from /home/sage/.rvm/gems/ruby-2.1.5/gems/activerecord-4.1.8/lib/active_record/connection_adapters/connection_specification.rb:187:in `spec'
	from /home/sage/.rvm/gems/ruby-2.1.5/gems/activerecord-4.1.8/lib/active_record/connection_handling.rb:50:in `establish_connection'
	from /home/sage/.rvm/gems/ruby-2.1.5/bundler/gems/activerecord-import-ce63b1f50420/lib/activerecord-import.rb:4:in `establish_connection_with_activerecord_import'
	from /home/sage/.rvm/gems/ruby-2.1.5/gems/activerecord-4.1.8/lib/active_record/railtie.rb:129:in `block (2 levels) in <class:Railtie>'
	from /home/sage/.rvm/gems/ruby-2.1.5/gems/activesupport-4.1.8/lib/active_support/lazy_load_hooks.rb:38:in `instance_eval'
	from /home/sage/.rvm/gems/ruby-2.1.5/gems/activesupport-4.1.8/lib/active_support/lazy_load_hooks.rb:38:in `execute_hook'
	from /home/sage/.rvm/gems/ruby-2.1.5/gems/activesupport-4.1.8/lib/active_support/lazy_load_hooks.rb:28:in `block in on_load'
	from /home/sage/.rvm/gems/ruby-2.1.5/gems/activesupport-4.1.8/lib/active_support/lazy_load_hooks.rb:27:in `each'
	from /home/sage/.rvm/gems/ruby-2.1.5/gems/activesupport-4.1.8/lib/active_support/lazy_load_hooks.rb:27:in `on_load'
	from /home/sage/.rvm/gems/ruby-2.1.5/gems/activerecord-4.1.8/lib/active_record/railtie.rb:118:in `block in <class:Railtie>'
	from /home/sage/.rvm/gems/ruby-2.1.5/gems/railties-4.1.8/lib/rails/initializable.rb:30:in `instance_exec'
	from /home/sage/.rvm/gems/ruby-2.1.5/gems/railties-4.1.8/lib/rails/initializable.rb:30:in `run'
	from /home/sage/.rvm/gems/ruby-2.1.5/gems/railties-4.1.8/lib/rails/initializable.rb:55:in `block in run_initializers'
	from /home/sage/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/tsort.rb:226:in `block in tsort_each'
	from /home/sage/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/tsort.rb:348:in `block (2 levels) in each_strongly_connected_component'
	from /home/sage/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/tsort.rb:427:in `each_strongly_connected_component_from'
	from /home/sage/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/tsort.rb:347:in `block in each_strongly_connected_component'
	from /home/sage/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/tsort.rb:345:in `each'
	from /home/sage/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/tsort.rb:345:in `call'
	from /home/sage/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/tsort.rb:345:in `each_strongly_connected_component'
	from /home/sage/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/tsort.rb:224:in `tsort_each'
	from /home/sage/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/tsort.rb:205:in `tsort_each'
	from /home/sage/.rvm/gems/ruby-2.1.5/gems/railties-4.1.8/lib/rails/initializable.rb:54:in `run_initializers'
	from /home/sage/.rvm/gems/ruby-2.1.5/gems/railties-4.1.8/lib/rails/application.rb:300:in `initialize!'
	from /home/sage/WikiEduDashboard/config/environment.rb:5:in `<top (required)>'
	from /home/sage/WikiEduDashboard/spec/rails_helper.rb:4:in `require'
	from /home/sage/WikiEduDashboard/spec/rails_helper.rb:4:in `<top (required)>'
	from /home/sage/WikiEduDashboard/spec/models/article_spec.rb:1:in `require'
	from /home/sage/WikiEduDashboard/spec/models/article_spec.rb:1:in `<top (required)>'
	from /home/sage/.rvm/gems/ruby-2.1.5/gems/rspec-core-3.1.7/lib/rspec/core/configuration.rb:1105:in `load'
	from /home/sage/.rvm/gems/ruby-2.1.5/gems/rspec-core-3.1.7/lib/rspec/core/configuration.rb:1105:in `block in load_spec_files'
	from /home/sage/.rvm/gems/ruby-2.1.5/gems/rspec-core-3.1.7/lib/rspec/core/configuration.rb:1105:in `each'
	from /home/sage/.rvm/gems/ruby-2.1.5/gems/rspec-core-3.1.7/lib/rspec/core/configuration.rb:1105:in `load_spec_files'
	from /home/sage/.rvm/gems/ruby-2.1.5/gems/rspec-core-3.1.7/lib/rspec/core/runner.rb:96:in `setup'
	from /home/sage/.rvm/gems/ruby-2.1.5/gems/rspec-core-3.1.7/lib/rspec/core/runner.rb:84:in `run'
	from /home/sage/.rvm/gems/ruby-2.1.5/gems/rspec-core-3.1.7/lib/rspec/core/runner.rb:69:in `run'
	from /home/sage/.rvm/gems/ruby-2.1.5/gems/rspec-core-3.1.7/lib/rspec/core/runner.rb:37:in `invoke'
	from /home/sage/.rvm/gems/ruby-2.1.5/gems/rspec-core-3.1.7/exe/rspec:4:in `<top (required)>'
	from /home/sage/.rvm/gems/ruby-2.1.5/bin/rspec:23:in `load'
	from /home/sage/.rvm/gems/ruby-2.1.5/bin/rspec:23:in `<main>'
	from /home/sage/.rvm/gems/ruby-2.1.5/bin/ruby_executable_hooks:15:in `eval'
	from /home/sage/.rvm/gems/ruby-2.1.5/bin/ruby_executable_hooks:15:in `<main>'

**Comment by ragesoss** [comment]
I think this took care of it: 3ff2e4a01d44a8f1e57744257e8c75285754a90a
