### ISSUE TITLE
Template error on signin

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#361]
One of the errors on Sentry may be related to the problems a few users have reported with signing in:
http://sentry.ragesoss.com:8080/wiki-ed/production/group/279/

```
Stacktrace (most recent call first):

  /var/www/dashboard/shared/bundle/ruby/2.1.0/gems/devise-3.4.1/app/views/devise/sessions/new.html.erb:3:in `__var_www_dashboard_shared_bundle_ruby_______gems_devise_______app_views_devise_sessions_new_html_erb__576277596_95123950'
    <%= form_for(resource, as: resource_name, url: session_path(resource_name)) do |f| %>
  action_view/template.rb:145:in `block in render'
    view.send(method_name, locals, buffer, &block)
  active_support/notifications.rb:161:in `instrument'
    yield payload if block_given?
  action_view/template.rb:339:in `instrument'
    ActiveSupport::Notifications.instrument("#{action}.action_view", payload, &block)
  action_view/template.rb:143:in `render'
    instrument("!render_template") do
  action_view/renderer/template_renderer.rb:55:in `block (2 levels) in render_template'
    template.render(view, locals) { |*name| view._layout_for(*name) }
  action_view/renderer/abstract_renderer.rb:38:in `block in instrument'
    ActiveSupport::Notifications.instrument("render_#{name}.action_view", options){ yield }
  active_support/notifications.rb:159:in `block in instrument'
    instrumenter.instrument(name, payload) { yield payload if block_given? }
  active_support/notifications/instrumenter.rb:20:in `instrument'
    yield payload
  active_support/notifications.rb:159:in `instrument'
    instrumenter.instrument(name, payload) { yield payload if block_given? }
  action_view/renderer/abstract_renderer.rb:38:in `instrument'
    ActiveSupport::Notifications.instrument("render_#{name}.action_view", options){ yield }
  action_view/renderer/template_renderer.rb:54:in `block in render_template'
    instrument(:template, :identifier => template.identifier, :layout => layout.try(:virtual_path)) do
  action_dispatch/middleware/request_id.rb:21:in `call'
    @app.call(env).tap { |_status, headers, _body| headers["X-Request-Id"] = env["action_dispatch.request_id"] }
  rack/methodoverride.rb:21:in `call'
    @app.call(env)
  rack/runtime.rb:17:in `call'
    status, headers, body = @app.call(env)
  active_support/cache/strategy/local_cache_middleware.rb:26:in `call'
    response = @app.call(env)
  rack/sendfile.rb:112:in `call'
    status, headers, body = @app.call(env)
  raven/integrations/rack.rb:54:in `call'
    response = @app.call(env)
  rails/engine.rb:514:in `call'
    app.call(env)
  rails/application.rb:144:in `call'
    super(env)
  /usr/local/rvm/gems/ruby-2.1.5/gems/passenger-4.0.57/lib/phusion_passenger/rack/thread_handler_extension.rb:74:in `process_request'
    status, headers, body = @app.call(env)
  /usr/local/rvm/gems/ruby-2.1.5/gems/passenger-4.0.57/lib/phusion_passenger/request_handler/thread_handler.rb:141:in `accept_and_process_next_request'
    process_request(headers, connection, socket_wrapper, @protocol == :http)
  /usr/local/rvm/gems/ruby-2.1.5/gems/passenger-4.0.57/lib/phusion_passenger/request_handler/thread_handler.rb:109:in `main_loop'
    hijacked = accept_and_process_next_request(socket_wrapper, channel, buffer)
  /usr/local/rvm/gems/ruby-2.1.5/gems/passenger-4.0.57/lib/phusion_passenger/request_handler.rb:455:in `block (3 levels) in start_threads'
    handler.main_loop(set_initialization_state_to_true)
```

**Comment by ragesoss** [comment]
Hmm... this seems to only happen on Chrome and Safari. Perhaps it's something WebKit specific? Still haven't figured out how to replicate it, though.

**Comment by thenickcox** [comment]
Here's an update on this. It's definitely not WebKit only; [here](http://sentry.ragesoss.com:8080/wiki-ed/production/group/279/events/18210/) is an instance of it on IE11. I was able to replicate it by going directly to "/sign_in", which routes to that Devise view, which indeed doesn't have a `session_path` because we don't define it. But I'm not sure how a user would get there without navigating there directly (unlikely); nothing in our app seems to link to there.

Nate followed [the directions](https://github.com/plataformatec/devise/wiki/OmniAuth%3A-Overview#using-omniauth-without-other-authentications) for OmniAuth-only authentication to a T, but the problem is going to "/sign_in," which I think we can prevent by [removing it from the routes](https://github.com/WikiEducationFoundation/WikiEduDashboard/blob/master/config/routes.rb#L13), but that may have unintended consequences. 

Right now, it doesn't make sense to me that it would disallow the sign in process, however.

**Comment by ragesoss** [comment]
This error has not shown up in 2 months. Whatever it was, we seem to have solved that aspect of it.
