### ISSUE TITLE
Intermittent test failure

### ISSUE THREAD

**Issue by bmathews** [WikiEducationFoundation/WikiEduDashboard#362]
```
Failures:
  1) Student users removing an assigned article should work
     Failure/Error: Unable to find matching line from backtrace
     VCR::Errors::UnhandledHTTPRequestError:
       
       
       ================================================================================
       An HTTP request has been made that VCR does not know how to handle:
         GET https://en.wikipedia.org/w/api.php?action=query&format=json&meta=tokens
       
       There is currently no cassette in use. There are a few ways
       you can configure VCR to handle this request:
       
         * If you're surprised VCR is raising this error
           and want insight about how VCR attempted to handle the request,
           you can use the debug_logger configuration option to log more details [1].
         * If you want VCR to record this request and play it back during future test
           runs, you should wrap your test (or this portion of your test) in a
           `VCR.use_cassette` block [2].
         * If you only want VCR to handle requests made while a cassette is in use,
           configure `allow_http_connections_when_no_cassette = true`. VCR will
           ignore this request since it is made when there is no cassette [3].
         * If you want VCR to ignore this request (and others like it), you can
           set an `ignore_request` callback [4].
       
       [1] https://www.relishapp.com/vcr/vcr/v/2-9-3/docs/configuration/debug-logging
       [2] https://www.relishapp.com/vcr/vcr/v/2-9-3/docs/getting-started
       [3] https://www.relishapp.com/vcr/vcr/v/2-9-3/docs/configuration/allow-http-connections-when-no-cassette
       [4] https://www.relishapp.com/vcr/vcr/v/2-9-3/docs/configuration/ignore-request
       ================================================================================
     # ./lib/wiki_edits.rb:214:in `get_tokens'
     # ./lib/wiki_edits.rb:164:in `post_whole_page'
     # ./lib/wiki_edits.rb:89:in `update_course'
     # ./app/controllers/users_controller.rb:46:in `save'
Finished in 9 minutes 3 seconds (files took 3.33 seconds to load)
211 examples, 1 failure, 3 pending
Failed examples:
rspec ./spec/features/student_role_spec.rb:158 # Student users removing an assigned article should work
Coverage = 97.65%. Sending report to https://codeclimate.com for branch master... done.
/home/travis/.rvm/rubies/ruby-2.1.5/bin/ruby -I/home/travis/build/WikiEducationFoundation/WikiEduDashboard/vendor/bundle/ruby/2.1.0/gems/rspec-core-3.1.7/lib:/home/travis/build/WikiEducationFoundation/WikiEduDashboard/vendor/bundle/ruby/2.1.0/gems/rspec-support-3.1.2/lib /home/travis/build/WikiEducationFoundation/WikiEduDashboard/vendor/bundle/ruby/2.1.0/gems/rspec-core-3.1.7/exe/rspec --pattern spec/\*\*\{,/\*/\*\*\}/\*_spec.rb failed
```

**Comment by ragesoss** [comment]
Similarly, over the last couple days, stats.grok.se has been intermittently unreliable and has caused a few builds to fail. (In the medium term, Wikimedia is expected to release a page views service that ought to be more reliable. We may need to rewrite the view import pipeline to take advantage of it, though.)

**Comment by ragesoss** [comment]
Here's a new one:
```
Failures:

  1) New course creation and editing course workflow should allow the user to create a course
     Failure/Error: expect(Course.last.weekdays).to eq('0001100')
       
       expected: "0001100"
            got: "0001000"
       
       (compared using ==)
     # ./spec/features/course_creation_spec.rb:183:in `block (3 levels) in <top (required)>'

Finished in 7 minutes 14 seconds (files took 3.08 seconds to load)
263 examples, 1 failure, 2 pending

Failed examples:

rspec ./spec/features/course_creation_spec.rb:88 # New course creation and editing course workflow should allow the user to create a course
Coverage = 98.74%. Sending report to https://codeclimate.com for branch CourseUpdateManager... done.
/home/travis/.rvm/rubies/ruby-2.1.5/bin/ruby -I/home/travis/build/WikiEducationFoundation/WikiEduDashboard/vendor/bundle/ruby/2.1.0/gems/rspec-core-3.1.7/lib:/home/travis/build/WikiEducationFoundation/WikiEduDashboard/vendor/bundle/ruby/2.1.0/gems/rspec-support-3.1.2/lib /home/travis/build/WikiEducationFoundation/WikiEduDashboard/vendor/bundle/ruby/2.1.0/gems/rspec-core-3.1.7/exe/rspec --pattern spec/\*\*\{,/\*/\*\*\}/\*_spec.rb failed
```

**Comment by ragesoss** [comment]
Another common one:

```
rspec ./spec/features/home_page_spec.rb:162 # the home page cohort pages should load courses from the right cohorts

  1) the home page cohort pages should load courses from the right cohorts
     Failure/Error: Unable to find matching line from backtrace
     ActionController::RoutingError:
       Course not found
     # ./app/helpers/course_helper.rb:6:in `find_course_by_slug'
     # ./app/controllers/courses_controller.rb:63:in `show'

**Comment by ragesoss** [comment]
Ever since Matt's refactor of the course cloned modal, the test for that has been particularly flaky, failing about half the time on travis: 0f875b65a1c953ba72f9d06918ddfe1f4f7735f0

```
  1) cloning a course copies relevant attributes of an existing course
     Failure/Error: expect(page).to have_content 'Course Successfully Cloned'
       expected to find text "Course Successfully Cloned" in "Home Recent Activity Ragesock. Log Out ARTICLES CREATED ARTICLES EDITED TOTAL EDITS STUDENT EDITORS CHARS ADDED ARTICLE VIEWS OVERVIEW TIMELINE STUDENTS ARTICLES UPLOADS ACTIVITY Edit Description Details Edit Details Instructors: Ragesock School: Term: Passcode: Expected Students: Start: End: Assignment Start: Assignment End: Cohorts: None Tags: None Actions Delete course Milestones This course does not currently have any milestones."
     # ./spec/features/course_creation_spec.rb:471:in `block (2 levels) in <top (required)>'
```

**Comment by adamwight** [comment]
This seems like a tracking bug, so I'll just dump an observation here.  Some of the flickering must be caused by a race condition with page load--which would explain why the much faster Phantom (or webkit?) tests fail and slugenium succeeds most of the time.  [This page](http://makandracards.com/makandra/12139-waiting-for-page-loads-and-ajax-requests-to-finish-with-capybara) gives a promising workaround, that we wait for the container we'll be testing to render:
```
wait_until do
  page.has_css?('.suggestions')
end
```

**Comment by ragesoss** [comment]
We've made a lot of progress with this; the remaining flickering tests were mainly around race conditions with the different ajax calls that fire off simultaneously on course load. It's been a little while since any tests failed without something being actually broken.

Next steps should be to revisit all the specs marked 'pending'. A few are now broken and need to be updated. The rest might be stable now.

**Comment by ragesoss** [comment]
The feature specs are pretty stable now, overall. Some tests still fail because of external API dependencies — when a Wikimedia or wmflabs service goes down, tests break. That's covered by #569. It's probably time to save some fixtures or mock those services.

Other than that, I think we can call this closed; if we find a flickering test that is not caused by external APIs, that should be considered a new bug.
