### ISSUE TITLE
Intermittently failing test: admin role spec, line 144

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#3710]
This feature spec is the most common cause of the integration tests failing when nothing is wrong / nothing changed:

```
rspec ./spec/features/admin_role_spec.rb:144 # Admin users linking a course to its Salesforce record makes the Link to Salesforce button appear
```

Typically it fails like this:
```
  1) Admin users linking a course to its Salesforce record makes the Link to Salesforce button appear

     Failure/Error:
       accept_prompt(with: 'https://cs54.salesforce.com/a0f1a011101Xyas?foo=bar') do
         click_button 'Link to Salesforce'
       end

     Capybara::ModalNotFound:
       Unable to find modal dialog

     # ./spec/features/admin_role_spec.rb:149:in `block (3 levels) in <top (required)>'
     # ------------------
     # --- Caused by: ---
     # Selenium::WebDriver::Error::TimeoutError:
     #   timed out after 2 seconds (no such alert
     #     (Session info: headless chrome=79.0.3945.130)
     #     (Driver info: chromedriver=79.0.3945.36 (3582db32b33893869b8c1339e8f4d9ed1816f143-refs/branch-heads/3945@{#614}),platform=Linux 4.15.0-1028-gcp x86_64))
     #   ./spec/features/admin_role_spec.rb:149:in `block (3 levels) in <top (required)>'
```

Find out why the test fails intermittently, and improve the test so that it's reliable.

**Comment by shashwatkathuria** [comment]
Tried many times but the test is passing in my machine. Is there any specific instance by chance to reproduce the issue? I did observe this error in many PRs.

![Screenshot from 2020-02-28 17-33-27](https://user-images.githubusercontent.com/37243661/75547293-901e2680-5a50-11ea-9c73-aa2d03404d84.png)

**Comment by shashwatkathuria** [comment]
Maybe increasing the selenium webdriver timeout (setting it manually) should solve the problem.

**Comment by ragesoss** [comment]
I don't think the timeline limit should be the problem; it does not take more than 2 seconds to render the modal. But I don't know how to consistently reproduce the issue. My guess is there's some other problem, a race condition that is keeping the modal from rendering in the cases where it fails.

**Comment by jproft** [comment]
@ragesoss I spent quite a bit of time trying to figure out why this test  -- along with the test given in #3988 -- intermittently fail. Although the failure modes seem different, the tests do both use the following:

- `click_button`
- `accept_prompt`

I noticed that there are only two other instances of `accept_prompt` in the tests: one in `course_creation_spec`, and the other in `campaign_overview_spec`. One distinguishing factor is that both of these use `find().click`, whereas the two that are intermittently failing use `click_button` to find what they want to click. `click_button` is used in many other places in the tests, but not in conjunction with `accept_prompt`, which leads me to wonder whether their combination is causing a problem. However, `click_button` just calls `find().click` under the hood, so it doesn't seem super likely. Do you know whether the `course_creation_spec` and `campaign_overview_spec` tests act flaky as well? If so, that would seem to pinpoint prompt dialogs as problematic.

One theory I had is that the dialog is occasionally getting dismissed prior to the attempt to accept it. I have been wondering whether the fact that prompt dialogs need to have keystrokes sent to them (whereas alert dialogs and confirm dialogs do not) could be causing issues. A keystroke could cause the dialog to close, at which point any attempt to accept the dialog would raise an error. (And Capybara does indeed attempt to accept the dialog after sending keys to it.)

In the long run, I think the best thing to do would be to not use `prompt` at all, or any native JS popup dialogs. An approach that is integrated with the rest of the UI would be much better, and probably would test more reliably, too.

**Comment by ragesoss** [comment]
I agree that getting rid of `prompt` would be nice... although doing it in a UI-integrated way does come with a cost in terms of code complexity. (We have a system for doing this right now using the `initiateConfirm` action and the `Confirm` component, but it's not very elegant to use.)

The keystroke issue seems like an unlikely source of the problem, but looking back at the previous discussion, it does occur to me that the problem indeed be with the 2 second timeout...

The default Capybara wait time (for Ajax requests) is 10 seconds and we don't modify that. This timeout seems to be the specific default for `accept_prompt`. And while it definitely doesn't take 2 seconds for the modal to render *once you click the button*, it could conceivably take more than 2 seconds for the button to render in the first place. `click_button` relies on the default wait time, giving the browser up to 10 seconds for the specified button to appear. But the `accept_prompt` maybe doesn't integrate with that waiting behavior; it will time out after two seconds if no prompt appears, regardless of what happens in the block it gets passed.

That is ulimately a problem of the combination of `click_button` with `accept_prompt` as you suggested. My guess is that this test (and any others that fail in similar circumstances) can be fixed if we expect the page to have the desired button before the `accept_prompt`, so that `click_button` won't have to do any waiting for the button to render. The other cases the use both of those methods are probably stable because other parts of the spec that any necessary waiting is already done before it reaches the `accept_prompt` block.

**Comment by ragesoss** [comment]
Well... so much for that theory. A spec failed today at the `accept_prompt`, even after adding the line looking for the button ahead of there. So the `Link to Salesforce` button appears, but the modal does not.
