### ISSUE TITLE
If there is a Block of type "milestone" on the Timeline that includes a training module, the Milestones component won't render

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#4718]
This bug breaks the Home tab, based on the contents of the Timeline.

Something in the Milestones component expects milestone block content to just be a String, and if there are assigned training modules on that block, it throws an error.

**Comment by aaditya9899** [comment]
hey i would like to work on this issue  but can you provide me the source to set up dev enviroument locally in my laptop?

**Comment by ragesoss** [comment]
@aaditya9899 you can find instructions for setting up a dev environment here: https://github.com/WikiEducationFoundation/WikiEduDashboard/blob/master/docs/setup.md

Depending on your operating system, you may be able to use the setup script, or you may need to go through the manual setup steps there. If you have any trouble using the setup script, please describe it here: https://github.com/WikiEducationFoundation/WikiEduDashboard/issues/1709

And if you run into any trouble with the manual setup, please describe it here: https://github.com/WikiEducationFoundation/WikiEduDashboard/issues/1351

**Comment by aaditya9899** [comment]
how to locate the file and code which i have to work upon and also how to check my code is working or not?

**Comment by ragesoss** [comment]
The main file here is `app/assets/javascripts/components/overview/milestones.jsx`.

You should be able to replicate the problem locally by creating a course, enabling the Timeline feature, adding a Week and Block to the timeline, then including a training module in the Block, then changing the Block type to 'milestone', then visiting the Home tab of the course (which is where the Milestones component is rendered).

**Comment by aaditya9899** [comment]
got it , i have setup the dev server, now from where i can find the problem you talked about, i mean how to create the course? 
Attaching the screenshot for your reference

![Untitled](https://user-images.githubusercontent.com/38832156/149475007-ce7c1967-6c7a-43be-bade-64dfd928bf9c.jpg)
.

**Comment by ragesoss** [comment]
@aaditya9899 you're not working on this one anymore, correct?

**Comment by aaditya9899** [comment]
@ragesoss yes I started working on GitHub actions instead because I was having difficulty in understanding it at that time but currently i am not working on it

**Comment by aaditya9899** [comment]
hey @ragesoss  i am working on this now but I am having little difficulty in creating the bug locally.

![bug](https://user-images.githubusercontent.com/38832156/154422955-c56888ba-96b1-4581-b747-ad0835e014a0.png)

**Comment by aaditya9899** [comment]
working on this one currently @ragesoss

**Comment by aaditya9899** [comment]
that part where milestone is written , that's the bug right?

![bug](https://user-images.githubusercontent.com/38832156/154423636-0ece4a59-b1a0-4a99-8c3d-2221bc52f6c0.png)

**Comment by aaditya9899** [comment]
working on this one currently

**Comment by aaditya9899** [comment]
just a little doubt that part where the milestone is written , that's the bug right , and also while adding it , i received a red warning too. The expected behaviour should be what exactly?

![ew](https://user-images.githubusercontent.com/38832156/154814025-79b4a197-4681-4fc1-a826-0db6d0ab35f9.png)

**Comment by aaditya9899** [comment]
hey @ragesoss the red error on assigning the milestone with training module got fixed with starting redis server

**Comment by aaditya9899** [comment]
I just want to know what will it look like on successful rendering of milestone component as I am not sure what's the bug exactly currently

**Comment by ragesoss** [comment]
You should be able to replicate the bug like this:

1. In `wiki_education` mode, create a new course that is several months long, and choose the 'research and write an article' option in the assignment wizard to create a timeline.
2. Go to the timeline tab, find one of the blocks that only contains an assigned training module and no other content, and edit this block to change the Type to 'Milestone'.
3. Go back to the Home tab for the course. If the bug is happening, the whole page will go blank except for the navbar, because of the error during rendering.

**Comment by aaditya9899** [comment]
I have enabled ` wiki_education mode : 'true'` but creating a course mean `creating an independent programme` ?

**Comment by aaditya9899** [comment]
can you explain the first step just in brief to do that? cause I am not sure about it

**Comment by aaditya9899** [comment]
wiki_education mode mean setting ` wiki_education: 'true'` in application.yml

**Comment by ragesoss** [comment]
If you're seeing 'create an independent program', you are not in `wiki_education` mode. Make sure you have `wiki_education: 'true'` in `application.yml. Then, on the "My Dashboard" homepage, you should have a "Create Course" button.

**Comment by ragesoss** [comment]
I'm not sure either. If you see 'Create an Independent Program' on the homepage, it's definitely not in `wiki_education` mode. If you see no buttons, try adding admin rights to your account.

**Comment by aaditya9899** [comment]
oh how to do that

**Comment by ragesoss** [comment]
See https://github.com/WikiEducationFoundation/WikiEduDashboard/blob/master/docs/user_roles.md#admin-permissions

**Comment by aaditya9899** [comment]
Thank you @ragesoss fixed the issue and now working on the bug

**Comment by aaditya9899** [comment]
not able to reproduce the bug , i also tried making a new block with type milestone and adding training module as well but still it is rendering fine

**Comment by ragesoss** [comment]
I couldn't replicate it either by editing the timeline, because it only happens when the the `content` of the `Block` is null; when I changed a training block to Milestone type, it had an empty string as the content. I was able to replicate it by updating the `content` to `nil` via Rails console.

**Comment by aaditya9899** [comment]
oh how to do that via rail console?

**Comment by ragesoss** [comment]
Figure out the block's ID (which you can do by inspecting the timeline.json output for the course, or by using the Redux Dev Tools extension for Chrome), then in a rails console, you can some some something like:

```ruby
block = Block.find(123)
block.update(content: nil)
```

**Comment by ragesoss** [comment]
that looks like a plain `irb` console, not a rails console. Try `bundle exec rails c` to launch a rails console.

**Comment by aaditya9899** [comment]
thankx bug is reproduced now

**Comment by aaditya9899** [comment]
what does this code do   `  const rawHtml = md.render(block.content);`

**Comment by ragesoss** [comment]
It converts the the block content (which is in Markdown format) into HTML.

**Comment by aaditya9899** [comment]
> It converts the the block content (which is in Markdown format) into HTML.

oh okay I was referring to your hint that something expecting milestone component to be just string and wondering where it is coming from that's why asked

**Comment by aaditya9899** [comment]
Now looking at the console I got these tips 
`
     Error: Input data should be a String

      at b.parse (index.js:519:11)

    at b.render (index.js:544:36)
    at milestones.jsx:34:28
    at Array.map (<anonymous>)
    at milestones.jsx:31:30
    at Array.map (<anonymous>)
    
I think I can solve this now

**Comment by aaditya9899** [comment]
hey @ragesoss My changes in vscode in not reflecting in the live server?? When I check the code in the source window of console panel of chrome , it still shows the previous code

**Comment by ragesoss** [comment]
It sounds like you haven't compiled the assets. If you have `yarn start` running in a terminal, it will compile the assets and then recompile any time there is a change. If you run `yarn build` and wait for it to exit, it will compile the production version of the assets.

**Comment by aaditya9899** [comment]
okay but its taking too long to complete yarn start , I have to exit it after 10 min or so because it was not moving further

**Comment by ragesoss** [comment]
`yarn start` doesn't exit, it just keeps running and watches for changes, automatically recompiling each time you save a JS or CSS change.

**Comment by aaditya9899** [comment]
ohh okay thank you so much for clarity .

**Comment by aaditya9899** [comment]
on replacing  `const milestoneBlocks = filter(week.blocks, block => block.kind === this.milestoneBlockType);`
with `const milestoneBlocks = [ ] ;` , the milestone component is not getting but the screen is appearing , this command filter out on basis of what

**Comment by ragesoss** [comment]
The big is that the whole Home tab disappears. A fix will mean a Milestone with null content and a training module will no longer crash the whole Home tab

**Comment by aaditya9899** [comment]
hmm yes I have fixed it by not rendering it on the hometab but having difficulty in not making tab disappear as well as keeping that also, let me see what I can do
