### ISSUE TITLE
In development environment, there are warnings and errors when starting `guard`

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#5645]
### What is happening?
When I start `guard` for a local development server, I get the following output:

```
Warning: you have a Gemfile, but you're not using bundler or RUBYGEMS_GEMDEPS
11:03:12 - INFO -
> [#] Guard here! It looks like your project has a Gemfile, yet you are running
> [#] `guard` outside of Bundler. If this is your intent, feel free to ignore this
> [#] message. Otherwise, consider using `bundle exec guard` to ensure your
> [#] dependencies are loaded correctly.
> [#] (You can run `guard` with --no-bundler-warning to get rid of this message.)
11:03:13 - INFO - Bundle already up-to-date
11:03:13 - INFO - [Guard::Rails] will start the default web server on port 3000 in development.
11:03:13 - INFO - Starting Rails...

=> Booting Puma
=> Rails 7.0.7 application starting in development 
=> Run `bin/rails server --help` for more startup options
Redis#sadd will always return an Integer in Redis 5.0.0. Use Redis#sadd? instead.(called from: /home/sage/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/sidekiq-cron-1.7.0/lib/sidekiq/cron/job.rb:468:in `block in save')
2024-02-12T19:03:14.435Z pid=1422661 tid=ug71 INFO: Cron Jobs - added job with name: schedule_course_updates
Redis#sadd will always return an Integer in Redis 5.0.0. Use Redis#sadd? instead.(called from: /home/sage/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/sidekiq-cron-1.7.0/lib/sidekiq/cron/job.rb:468:in `block in save')
2024-02-12T19:03:14.436Z pid=1422661 tid=ug71 INFO: Cron Jobs - added job with name: update_constantly
Redis#sadd will always return an Integer in Redis 5.0.0. Use Redis#sadd? instead.(called from: /home/sage/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/sidekiq-cron-1.7.0/lib/sidekiq/cron/job.rb:468:in `block in save')
2024-02-12T19:03:14.436Z pid=1422661 tid=ug71 INFO: Cron Jobs - added job with name: update_daily
Redis#sadd will always return an Integer in Redis 5.0.0. Use Redis#sadd? instead.(called from: /home/sage/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/sidekiq-cron-1.7.0/lib/sidekiq/cron/job.rb:468:in `block in save')
2024-02-12T19:03:14.437Z pid=1422661 tid=ug71 INFO: Cron Jobs - added job with name: survey_emails
Redis#sadd will always return an Integer in Redis 5.0.0. Use Redis#sadd? instead.(called from: /home/sage/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/sidekiq-cron-1.7.0/lib/sidekiq/cron/job.rb:468:in `block in save')
2024-02-12T19:03:14.438Z pid=1422661 tid=ug71 INFO: Cron Jobs - added job with name: open_ticket_emails
Puma starting in single mode...
* Puma version: 5.6.5 (ruby 3.1.2-p20) ("Birdie's Version")
*  Min threads: 0
*  Max threads: 5
*  Environment: development
*          PID: 1422661
* Listening on http://127.0.0.1:3000
* Listening on http://[::1]:3000
Use Ctrl-C to stop
11:03:16 - INFO - Rails started, pid 1422661

11:03:16 - INFO - Guard::RSpec is running
=> ERROR: couldn't load "./config/environment.rb"

Gem::LoadError => You have already activated strscan 3.0.4, but your Gemfile requires strscan 3.0.1. Prepending `bundle exec` to your command may solve this.
/home/sage/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.22/lib/bundler/runtime.rb:308:in `check_for_activated_spec!'
/home/sage/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.22/lib/bundler/runtime.rb:25:in `block in setup'
/home/sage/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.22/lib/bundler/spec_set.rb:155:in `each'
/home/sage/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.22/lib/bundler/spec_set.rb:155:in `each'
/home/sage/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.22/lib/bundler/runtime.rb:24:in `map'
/home/sage/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.22/lib/bundler/runtime.rb:24:in `setup'
/home/sage/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.22/lib/bundler.rb:162:in `setup'
/home/sage/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.22/lib/bundler/setup.rb:10:in `block in <top (required)>'
/home/sage/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.22/lib/bundler/ui/shell.rb:136:in `with_level'
/home/sage/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.22/lib/bundler/ui/shell.rb:88:in `silence'
/home/sage/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.22/lib/bundler/setup.rb:10:in `<top (required)>'
<internal:/home/sage/.rbenv/versions/3.1.2/lib/ruby/site_ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
<internal:/home/sage/.rbenv/versions/3.1.2/lib/ruby/site_ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
/home/sage/WikiEduDashboard/config/boot.rb:4:in `<top (required)>'
<internal:/home/sage/.rbenv/versions/3.1.2/lib/ruby/site_ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
<internal:/home/sage/.rbenv/versions/3.1.2/lib/ruby/site_ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
/home/sage/WikiEduDashboard/config/application.rb:1:in `<top (required)>'
<internal:/home/sage/.rbenv/versions/3.1.2/lib/ruby/site_ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
<internal:/home/sage/.rbenv/versions/3.1.2/lib/ruby/site_ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
/home/sage/WikiEduDashboard/config/environment.rb:2:in `<top (required)>'
/home/sage/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/i18n-js-4.2.2/lib/i18n-js/cli/command.rb:73:in `load'
/home/sage/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/i18n-js-4.2.2/lib/i18n-js/cli/command.rb:73:in `require_without_warnings'
/home/sage/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/i18n-js-4.2.2/lib/i18n-js/cli/command.rb:53:in `load_require_file!'
/home/sage/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/i18n-js-4.2.2/lib/i18n-js/cli/export_command.rb:73:in `block (2 levels) in <class:ExportCommand>'
/home/sage/.rbenv/versions/3.1.2/lib/ruby/3.1.0/benchmark.rb:311:in `realtime'
/home/sage/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/i18n-js-4.2.2/lib/i18n-js/cli/export_command.rb:72:in `block in <class:ExportCommand>'
/home/sage/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/i18n-js-4.2.2/lib/i18n-js/cli/command.rb:35:in `call'
/home/sage/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/i18n-js-4.2.2/lib/i18n-js/cli.rb:29:in `call'
/home/sage/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/i18n-js-4.2.2/exe/i18n:5:in `<top (required)>'
/home/sage/.rbenv/versions/3.1.2/bin/i18n:25:in `load'
/home/sage/.rbenv/versions/3.1.2/bin/i18n:25:in `<main>'
11:03:16 - INFO - Guard is now watching at '/home/sage/WikiEduDashboard'
```

The development environment still works, but those errors and warnings should be fixed.

**Comment by ragesoss** [comment]
Oh, I only get that error when I run `guard` instead of `bundle exec guard`, so it's using the default system strscan rather than the version from the Gemfile. You can disregard that one, as `bundle exec guard` is the supported way to run the server.

**Comment by DanAletor** [comment]
Hi @ragesoss, I would love to work on this

**Comment by ragesoss** [comment]
@DanAletor I'm not sure there are any remaining warnings, but if you find any, please post details about them in this thread, and then feel free to work on them.
