### ISSUE TITLE
Errors commonly break rake tasks

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#64]
Here's what I've found in the logs since the last deployment:
----
SocketError: getaddrinfo: No address associated with hostname
/var/www/dashboard-testing/releases/20150406220155/lib/grok.rb:36:in `api_get'
/var/www/dashboard-testing/releases/20150406220155/lib/grok.rb:13:in `views_for_article'
/var/www/dashboard-testing/releases/20150406220155/app/models/article.rb:131:in `block (3 levels) in update_views'
Tasks: TOP => article:update_new_article_views

----

[2015-04-07 06:00:12.332 INFO ] Daily update tasks are beginning.
[2015-04-07 06:00:12.337 INFO ] Updating article views
rake aborted!
Errno::ENOENT: No such file or directory @ unlink_internal - tmp/batch_pause.pid
/var/www/dashboard-testing/releases/20150406220155/lib/tasks/batch.rake:76:in `delete'
/var/www/dashboard-testing/releases/20150406220155/lib/tasks/batch.rake:76:in `ensure in block (2 levels) in <top (required)>'
/var/www/dashboard-testing/releases/20150406220155/lib/tasks/batch.rake:76:in `block (2 levels) in <top (required)>'
Circular dependency detected while autoloading constant Utils
/var/www/dashboard-testing/shared/bundle/ruby/2.1.0/gems/activesupport-4.1.8/lib/active_support/dependencies.rb:478:in `load_missing_constant'
/var/www/dashboard-testing/shared/bundle/ruby/2.1.0/gems/activesupport-4.1.8/lib/active_support/dependencies.rb:180:in `const_missing'
/var/www/dashboard-testing/shared/bundle/ruby/2.1.0/gems/activesupport-4.1.8/lib/active_support/dependencies.rb:512:in `load_missing_constant'
/var/www/dashboard-testing/shared/bundle/ruby/2.1.0/gems/activesupport-4.1.8/lib/active_support/dependencies.rb:180:in `const_missing'
/var/www/dashboard-testing/releases/20150406220155/lib/grok.rb:15:in `views_for_article'
/var/www/dashboard-testing/releases/20150406220155/app/models/article.rb:131:in `block (3 levels) in update_views'
Tasks: TOP => batch:update_daily

----

rake aborted!
Errno::ENOENT: No such file or directory @ unlink_internal - tmp/batch_pause.pid
/var/www/dashboard-testing/releases/20150403164213/lib/tasks/batch.rake:57:in `delete'
/var/www/dashboard-testing/releases/20150403164213/lib/tasks/batch.rake:57:in `block (2 levels) in <top (required)>'
Tasks: TOP => batch:update_daily

----

[2015-04-06 19:16:17.579 INFO ] Updating user names, global ids, and training status
rake aborted!
Zlib::BufError: buffer error
/var/www/dashboard-testing/releases/20150406220155/lib/replica.rb:148:in `api_get'
/var/www/dashboard-testing/releases/20150406220155/lib/replica.rb:81:in `get_revisions_raw'
/var/www/dashboard-testing/releases/20150406220155/lib/replica.rb:18:in `get_revisions'
/var/www/dashboard-testing/releases/20150406220155/app/models/revision.rb:29:in `block (2 levels) in update_all_revisions'
/var/www/dashboard-testing/releases/20150406220155/lib/utils.rb:9:in `block in chunk_requests'
/var/www/dashboard-testing/releases/20150406220155/lib/utils.rb:8:in `each'
/var/www/dashboard-testing/releases/20150406220155/lib/utils.rb:8:in `chunk_requests'
/var/www/dashboard-testing/releases/20150406220155/app/models/revision.rb:28:in `block in update_all_revisions'
/var/www/dashboard-testing/shared/bundle/ruby/2.1.0/gems/activerecord-4.1.8/lib/active_record/relation/delegation.rb:46:in `each'
/var/www/dashboard-testing/shared/bundle/ruby/2.1.0/gems/activerecord-4.1.8/lib/active_record/relation/delegation.rb:46:in `each'
/var/www/dashboard-testing/releases/20150406220155/app/models/revision.rb:23:in `update_all_revisions'
/var/www/dashboard-testing/releases/20150406220155/lib/tasks/revision.rake:5:in `block (2 levels) in <top (required)>'
/var/www/dashboard-testing/releases/20150406220155/lib/tasks/batch.rake:28:in `block (2 levels) in <top (required)>'
Net::ReadTimeout: Net::ReadTimeout
/var/www/dashboard-testing/releases/20150406220155/lib/replica.rb:148:in `api_get'
/var/www/dashboard-testing/releases/20150406220155/lib/replica.rb:81:in `get_revisions_raw'
/var/www/dashboard-testing/releases/20150406220155/lib/replica.rb:18:in `get_revisions'
/var/www/dashboard-testing/releases/20150406220155/app/models/revision.rb:29:in `block (2 levels) in update_all_revisions'
/var/www/dashboard-testing/releases/20150406220155/lib/utils.rb:9:in `block in chunk_requests'
/var/www/dashboard-testing/releases/20150406220155/lib/utils.rb:8:in `each'
/var/www/dashboard-testing/releases/20150406220155/lib/utils.rb:8:in `chunk_requests'
/var/www/dashboard-testing/releases/20150406220155/app/models/revision.rb:28:in `block in update_all_revisions'
/var/www/dashboard-testing/shared/bundle/ruby/2.1.0/gems/activerecord-4.1.8/lib/active_record/relation/delegation.rb:46:in `each'
/var/www/dashboard-testing/shared/bundle/ruby/2.1.0/gems/activerecord-4.1.8/lib/active_record/relation/delegation.rb:46:in `each'
/var/www/dashboard-testing/releases/20150406220155/app/models/revision.rb:23:in `update_all_revisions'
/var/www/dashboard-testing/releases/20150406220155/lib/tasks/revision.rake:5:in `block (2 levels) in <top (required)>'
/var/www/dashboard-testing/releases/20150406220155/lib/tasks/batch.rake:28:in `block (2 levels) in <top (required)>'
IO::EAGAINWaitReadable: Resource temporarily unavailable - read would block
/var/www/dashboard-testing/releases/20150406220155/lib/replica.rb:148:in `api_get'
/var/www/dashboard-testing/releases/20150406220155/lib/replica.rb:81:in `get_revisions_raw'
/var/www/dashboard-testing/releases/20150406220155/lib/replica.rb:18:in `get_revisions'
/var/www/dashboard-testing/releases/20150406220155/app/models/revision.rb:29:in `block (2 levels) in update_all_revisions'
/var/www/dashboard-testing/releases/20150406220155/lib/utils.rb:9:in `block in chunk_requests'
/var/www/dashboard-testing/releases/20150406220155/lib/utils.rb:8:in `each'
/var/www/dashboard-testing/releases/20150406220155/lib/utils.rb:8:in `chunk_requests'
/var/www/dashboard-testing/releases/20150406220155/app/models/revision.rb:28:in `block in update_all_revisions'
/var/www/dashboard-testing/shared/bundle/ruby/2.1.0/gems/activerecord-4.1.8/lib/active_record/relation/delegation.rb:46:in `each'
/var/www/dashboard-testing/shared/bundle/ruby/2.1.0/gems/activerecord-4.1.8/lib/active_record/relation/delegation.rb:46:in `each'
/var/www/dashboard-testing/releases/20150406220155/app/models/revision.rb:23:in `update_all_revisions'
/var/www/dashboard-testing/releases/20150406220155/lib/tasks/revision.rake:5:in `block (2 levels) in <top (required)>'
/var/www/dashboard-testing/releases/20150406220155/lib/tasks/batch.rake:28:in `block (2 levels) in <top (required)>'
Tasks: TOP => revision:update_revisions

----

And this one from production:

[2015-04-05 02:00:05.188 INFO ] Updating all courses
rake aborted!
MediaWiki::Unauthorized: Login failed: WrongToken
/var/www/dashboard/shared/bundle/ruby/2.1.0/gems/mediawiki-gateway-1.0.0/lib/media_wiki/gateway.rb:162:in `block in make_api_request'
/var/www/dashboard/shared/bundle/ruby/2.1.0/gems/rest-client-1.7.2/lib/restclient/request.rb:493:in `call'
/var/www/dashboard/shared/bundle/ruby/2.1.0/gems/rest-client-1.7.2/lib/restclient/request.rb:493:in `process_result'
/var/www/dashboard/shared/bundle/ruby/2.1.0/gems/rest-client-1.7.2/lib/restclient/request.rb:421:in `block in transmit'
/var/www/dashboard/shared/bundle/ruby/2.1.0/gems/rest-client-1.7.2/lib/restclient/request.rb:413:in `transmit'
/var/www/dashboard/shared/bundle/ruby/2.1.0/gems/rest-client-1.7.2/lib/restclient/request.rb:176:in `execute'
/var/www/dashboard/shared/bundle/ruby/2.1.0/gems/rest-client-1.7.2/lib/restclient/request.rb:41:in `execute'
/var/www/dashboard/shared/bundle/ruby/2.1.0/gems/mediawiki-gateway-1.0.0/lib/media_wiki/gateway.rb:182:in `http_send'
/var/www/dashboard/shared/bundle/ruby/2.1.0/gems/mediawiki-gateway-1.0.0/lib/media_wiki/gateway.rb:130:in `make_api_request'
/var/www/dashboard/shared/bundle/ruby/2.1.0/gems/mediawiki-gateway-1.0.0/lib/media_wiki/gateway.rb:156:in `block in make_api_request'
/var/www/dashboard/shared/bundle/ruby/2.1.0/gems/rest-client-1.7.2/lib/restclient/request.rb:493:in `call'
/var/www/dashboard/shared/bundle/ruby/2.1.0/gems/rest-client-1.7.2/lib/restclient/request.rb:493:in `process_result'
/var/www/dashboard/shared/bundle/ruby/2.1.0/gems/rest-client-1.7.2/lib/restclient/request.rb:421:in `block in transmit'
/var/www/dashboard/shared/bundle/ruby/2.1.0/gems/rest-client-1.7.2/lib/restclient/request.rb:413:in `transmit'
/var/www/dashboard/shared/bundle/ruby/2.1.0/gems/rest-client-1.7.2/lib/restclient/request.rb:176:in `execute'
/var/www/dashboard/shared/bundle/ruby/2.1.0/gems/rest-client-1.7.2/lib/restclient/request.rb:41:in `execute'
/var/www/dashboard/shared/bundle/ruby/2.1.0/gems/mediawiki-gateway-1.0.0/lib/media_wiki/gateway.rb:182:in `http_send'
/var/www/dashboard/shared/bundle/ruby/2.1.0/gems/mediawiki-gateway-1.0.0/lib/media_wiki/gateway.rb:130:in `make_api_request'
/var/www/dashboard/shared/bundle/ruby/2.1.0/gems/mediawiki-gateway-1.0.0/lib/media_wiki/gateway.rb:156:in `block in make_api_request'
/var/www/dashboard/shared/bundle/ruby/2.1.0/gems/rest-client-1.7.2/lib/restclient/request.rb:493:in `call'
/var/www/dashboard/shared/bundle/ruby/2.1.0/gems/rest-client-1.7.2/lib/restclient/request.rb:493:in `process_result'
/var/www/dashboard/shared/bundle/ruby/2.1.0/gems/rest-client-1.7.2/lib/restclient/request.rb:421:in `block in transmit'
/var/www/dashboard/shared/bundle/ruby/2.1.0/gems/rest-client-1.7.2/lib/restclient/request.rb:413:in `transmit'
/var/www/dashboard/shared/bundle/ruby/2.1.0/gems/rest-client-1.7.2/lib/restclient/request.rb:176:in `execute'
/var/www/dashboard/shared/bundle/ruby/2.1.0/gems/rest-client-1.7.2/lib/restclient/request.rb:41:in `execute'
/var/www/dashboard/shared/bundle/ruby/2.1.0/gems/mediawiki-gateway-1.0.0/lib/media_wiki/gateway.rb:182:in `http_send'
/var/www/dashboard/shared/bundle/ruby/2.1.0/gems/mediawiki-gateway-1.0.0/lib/media_wiki/gateway.rb:130:in `make_api_request'
/var/www/dashboard/shared/bundle/ruby/2.1.0/gems/mediawiki-gateway-1.0.0/lib/media_wiki/gateway.rb:65:in `send_request'
/var/www/dashboard/shared/bundle/ruby/2.1.0/gems/mediawiki-gateway-1.0.0/lib/media_wiki/gateway/users.rb:16:in `login'
/var/www/dashboard/releases/20150322183024/lib/wiki.rb:185:in `gateway'
/var/www/dashboard/releases/20150322183024/lib/wiki.rb:197:in `api_get'
/var/www/dashboard/releases/20150322183024/lib/wiki.rb:147:in `get_course_info_raw'
/var/www/dashboard/releases/20150322183024/lib/wiki.rb:21:in `get_course_info'
/var/www/dashboard/releases/20150322183024/app/models/course.rb:112:in `block in update_all_courses'
/var/www/dashboard/releases/20150322183024/lib/utils.rb:9:in `block in chunk_requests'
/var/www/dashboard/releases/20150322183024/lib/utils.rb:8:in `each'
/var/www/dashboard/releases/20150322183024/lib/utils.rb:8:in `chunk_requests'
/var/www/dashboard/releases/20150322183024/app/models/course.rb:112:in `update_all_courses'
/var/www/dashboard/releases/20150322183024/lib/tasks/course.rake:5:in `block (2 levels) in <top (required)>'
/var/www/dashboard/releases/20150322183024/lib/tasks/batch.rake:17:in `block (2 levels) in <top (required)>'
Tasks: TOP => course:update_courses

**Comment by ragesoss** [comment]
Here's another one, when the Wikimedia API is down:

MediaWiki::Exception: Bad response: [HTML for Mediawiki 503 error page]



Stacktrace (most recent call first):

  media_wiki/gateway.rb:203:in `get_response'
    raise APIError.new(*error.attributes.values_at(*%w[code info]))
  media_wiki/gateway.rb:142:in `block in make_api_request'
    doc = get_response(response.dup)
  restclient/request.rb:493:in `call'
    block.call(response, self, res, & block)
  restclient/request.rb:493:in `process_result'
    block.call(response, self, res, & block)
  restclient/request.rb:421:in `block in transmit'
    process_result res, & block
  net/http.rb:853:in `start'
    return yield(self)
  restclient/request.rb:413:in `transmit'
    net.start do |http|
  restclient/request.rb:176:in `execute'
    transmit uri, net_http_request_class(method).new(uri.request_uri, processed_headers), payload, & block
  restclient/request.rb:41:in `execute'
    new(args).execute(& block)
  media_wiki/gateway.rb:182:in `http_send'
    RestClient::Request.execute(opts, &block)
  media_wiki/gateway.rb:130:in `make_api_request'
    http_send(@wiki_url, form_data, @headers.merge(cookies: @cookies)) { |response, &block|
  media_wiki/gateway.rb:134:in `block in make_api_request'
    make_api_request(form_data, continue_xpath, retry_count + 1)
  rake/application.rb:106:in `each'
    top_level_tasks.each { |task_name| invoke_task(task_name) }
  rake/application.rb:106:in `block in top_level'
    top_level_tasks.each { |task_name| invoke_task(task_name) }
  rake/application.rb:115:in `run_with_threads'
    yield
  rake/application.rb:100:in `top_level'
    run_with_threads do
  rake/application.rb:78:in `block in run'
    top_level
  rake/application.rb:176:in `standard_exception_handling'
    yield
  rake/application.rb:75:in `run'
    standard_exception_handling do
  /home/sage/.rvm/gems/ruby-2.1.5/gems/rake-10.4.2/bin/rake:33:in `<top (required)>'
    Rake.application.run
  /home/sage/.rvm/gems/ruby-2.1.5/bin/rake:23:in `load'
    load Gem.bin_path('rake', 'rake', version)
  /home/sage/.rvm/gems/ruby-2.1.5/bin/rake:23:in `<main>'
    load Gem.bin_path('rake', 'rake', version)
  /home/sage/.rvm/gems/ruby-2.1.5/bin/ruby_executable_hooks:15:in `eval'
    eval File.read($0), binding, $0
  /home/sage/.rvm/gems/ruby-2.1.5/bin/ruby_executable_hooks:15:in `<main>'
    eval File.read($0), binding, $0
