### ISSUE TITLE
Revision.update_all_revisions fails on course with no revisions

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#81]
This appeared today for both production and staging: 

Stacktrace (most recent call first):

  app/models/revision.rb:30:in `block in update_all_revisions'
    start = c.revisions.order('date DESC').first.date.strftime('%Y%m%d')
  active_record/relation/delegation.rb:46:in `each'
    delegate :to_xml, :to_yaml, :length, :collect, :map, :each, :all?, :include?, :to_ary, :join, to: :to_a
  active_record/relation/delegation.rb:46:in `each'
    delegate :to_xml, :to_yaml, :length, :collect, :map, :each, :all?, :include?, :to_ary, :join, to: :to_a
  app/models/revision.rb:23:in `update_all_revisions'
    courses.each do |c|
  lib/tasks/revision.rake:5:in `block (2 levels) in <top (required)>'
    Revision.update_all_revisions
  rake/task.rb:240:in `call'
    act.call(self, args)
  rake/task.rb:240:in `block in execute'
    act.call(self, args)
  rake/task.rb:235:in `each'
    @actions.each do |act|
  rake/task.rb:235:in `execute'
    @actions.each do |act|
  rake/task.rb:179:in `block in invoke_with_call_chain'
    execute(task_args) if needed?
  monitor.rb:211:in `mon_synchronize'
    yield
  rake/task.rb:172:in `invoke_with_call_chain'
    @lock.synchronize do
  rake/application.rb:150:in `invoke_task'
    t.invoke(*args)
  rake/application.rb:106:in `block (2 levels) in top_level'
    top_level_tasks.each { |task_name| invoke_task(task_name) }
  rake/application.rb:106:in `each'
    top_level_tasks.each { |task_name| invoke_task(task_name) }
  rake/application.rb:106:in `block in top_level'
    top_level_tasks.each { |task_name| invoke_task(task_name) }
  rake/application.rb:115:in `run_with_threads'
    yield
  rake/application.rb:100:in `top_level'
    run_with_threads do
  rake/application.rb:78:in `block in run'
    top_level
  rake/application.rb:176:in `standard_exception_handling'
    yield
  rake/application.rb:75:in `run'
    standard_exception_handling do
  /var/www/dashboard/shared/bundle/ruby/2.1.0/gems/rake-10.4.2/bin/rake:33:in `<top (required)>'
    Rake.application.run
  /var/www/dashboard/shared/bundle/ruby/2.1.0/bin/rake:23:in `load'
    load Gem.bin_path('rake', 'rake', version)
  /var/www/dashboard/shared/bundle/ruby/2.1.0/bin/rake:23:in `<main>'
    load Gem.bin_path('rake', 'rake', version)

**Comment by ragesoss** [comment]
Resolved in 289e2bd639f45447ef1ab0f251356a02b086aa03
