### ISSUE TITLE
WikiEdits should handle Wikimedia API downtime gracefully

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#995]
Currently, it causes errors: https://sentry.wikiedu.org/wikiedu/production/issues/967/

```
JSON::ParserError: 784: unexpected token at '<!DOCTYPE html>
<html lang=en>
<meta charset=utf-8>
<title>Wikimedia Error</title>
<style>
* { margin: 0; padding: 0; }
body { background: #fff; font: 15px/1.6 sans-serif; color: #333; }
.content { margin: 7% auto 0; padding: 2em 1em 1em; max-width: 640px; }
.footer { clear: both; margin-top: 14%; border-top: 1px solid #e5e5e5; background: #f9f9f9; padding: 2em 0; font-size: 0.8em; text-align: center; }
img { float: left; margin: 0 2em 2em 0; }
a img { border: 0; }
h1 { margin-top: 1em; font-size: 1.2em; }
p { margin: 0.7em 0 1em 0; }
a { color: #0645AD; text-decoration: none; }
a:hover { text-decoration: underline; }
code { font-family: sans-serif; }
.text-muted { color: #777; }
</style>
<div class="content" role="main">
<a href="//www.wikimedia.org"><img src="//www.wikimedia.org/static/images/wmf.png" srcset="//www.wikimedia.org/static/images/wmf-2x.png 2x" alt=Wikimedia width=135 height=135></a>
<h1>Error</h1>
<p>Our servers are currently under maintenance or experiencing a technical problem. Please <a href="" title="Reload this page" onclick="window.location.reload(false); return false">try again</a> in a few&nbsp;minutes.</p><p>See the error message at the bottom of this page for more&nbsp;information.</p>
</div>
<div class="footer">
<p>If you report this error to the Wikimedia System Administrators, please include the details below.</p>
<p class="text-muted"><code>
Request from 2600:3c03::f03c:91ff:fe08:7973 via cp1053 cp1053, Varnish XID 741374242<br>Error: 503, Service Unavailable at Tue, 08 Nov 2016 13:49:01 GMT</code></p></div></html>'
  from /usr/local/rvm/gems/ruby-2.3.1/gems/passenger-5.0.29/src/ruby_supportlib/phusion_passenger/utils.rb:113:in `block in create_thread_and_abort_on_exception'
  from /usr/local/rvm/gems/ruby-2.3.1/gems/passenger-5.0.29/src/ruby_supportlib/phusion_passenger/request_handler.rb:416:in `block (3 levels) in start_threads'
  from /usr/local/rvm/gems/ruby-2.3.1/gems/passenger-5.0.29/src/ruby_supportlib/phusion_passenger/request_handler/thread_handler.rb:113:in `main_loop'
  from /usr/local/rvm/gems/ruby-2.3.1/gems/passenger-5.0.29/src/ruby_supportlib/phusion_passenger/request_handler/thread_handler.rb:152:in `accept_and_process_next_request'
  from /usr/local/rvm/gems/ruby-2.3.1/gems/passenger-5.0.29/src/ruby_supportlib/phusion_passenger/rack/thread_handler_extension.rb:97:in `process_request'
  from new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  from rails/engine.rb:522:in `call'
  from new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  from raven/integrations/rack.rb:50:in `call'
  from new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  from rack/sendfile.rb:111:in `call'
  from new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  from action_dispatch/middleware/static.rb:136:in `call'
  from new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  from action_dispatch/middleware/executor.rb:12:in `call'
  from new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  from active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
  from new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  from rack/runtime.rb:22:in `call'
  from new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  from rack/method_override.rb:22:in `call'
  from new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  from action_dispatch/middleware/request_id.rb:24:in `call'
  from new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  from request_store/middleware.rb:9:in `call'
  from new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  from rails/rack/logger.rb:24:in `call'
  from active_support/tagged_logging.rb:70:in `tagged'
  from active_support/tagged_logging.rb:26:in `tagged'
  from active_support/tagged_logging.rb:70:in `block in tagged'
  from rails/rack/logger.rb:24:in `block in call'
  from rails/rack/logger.rb:36:in `call_app'
  from new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  from action_dispatch/middleware/show_exceptions.rb:31:in `call'
  from new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  from action_dispatch/middleware/debug_exceptions.rb:49:in `call'
  from new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  from action_dispatch/middleware/remote_ip.rb:79:in `call'
  from new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  from action_dispatch/middleware/callbacks.rb:36:in `call'
  from active_support/callbacks.rb:90:in `run_callbacks'
  from active_support/callbacks.rb:750:in `_run_call_callbacks'
  from active_support/callbacks.rb:97:in `__run_callbacks__'
  from action_dispatch/middleware/callbacks.rb:38:in `block in call'
  from new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  from action_dispatch/middleware/cookies.rb:613:in `call'
  from new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  from rack/session/abstract/id.rb:216:in `call'
  from rack/session/abstract/id.rb:222:in `context'
  from new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  from rack/head.rb:12:in `call'
  from new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  from rack/conditional_get.rb:25:in `call'
  from new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  from rack/etag.rb:25:in `call'
  from new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  from warden/manager.rb:34:in `call'
  from warden/manager.rb:34:in `catch'
  from warden/manager.rb:35:in `block in call'
  from new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  from new_relic/rack/browser_monitoring.rb:32:in `traced_call'
  from new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  from new_relic/rack/agent_hooks.rb:30:in `traced_call'
  from new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  from http_accept_language/middleware.rb:14:in `call'
  from new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  from omniauth/strategy.rb:164:in `call'
  from omniauth/strategy.rb:186:in `call!'
  from new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  from omniauth/strategy.rb:164:in `call'
  from omniauth/strategy.rb:186:in `call!'
  from new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  from action_dispatch/routing/route_set.rb:725:in `call'
  from action_dispatch/journey/router.rb:26:in `serve'
  from action_dispatch/journey/router.rb:26:in `each'
  from action_dispatch/journey/router.rb:39:in `block in serve'
  from action_dispatch/routing/route_set.rb:32:in `serve'
  from action_dispatch/routing/route_set.rb:50:in `dispatch'
  from action_controller/metal.rb:262:in `dispatch'
  from action_controller/metal.rb:190:in `dispatch'
  from action_view/rendering.rb:30:in `process'
  from abstract_controller/base.rb:126:in `process'
  from active_record/railties/controller_runtime.rb:18:in `process_action'
  from action_controller/metal/params_wrapper.rb:248:in `process_action'
  from action_controller/metal/instrumentation.rb:30:in `process_action'
  from active_support/notifications.rb:164:in `instrument'
  from active_support/notifications/instrumenter.rb:21:in `instrument'
  from active_support/notifications.rb:164:in `block in instrument'
  from action_controller/metal/instrumentation.rb:32:in `block in process_action'
  from action_controller/metal/rescue.rb:20:in `process_action'
  from abstract_controller/callbacks.rb:19:in `process_action'
  from active_support/callbacks.rb:90:in `run_callbacks'
  from active_support/callbacks.rb:750:in `_run_process_action_callbacks'
  from active_support/callbacks.rb:101:in `__run_callbacks__'
  from active_support/callbacks.rb:455:in `call'
  from active_support/callbacks.rb:506:in `block (2 levels) in compile'
  from active_support/callbacks.rb:126:in `call'
  from abstract_controller/callbacks.rb:20:in `block in process_action'
  from action_controller/metal/rendering.rb:30:in `process_action'
  from abstract_controller/base.rb:188:in `process_action'
  from action_controller/metal/basic_implicit_render.rb:4:in `send_action'
  from app/controllers/courses_controller.rb:63:in `show'
  from app/controllers/courses_controller.rb:193:in `verify_edit_credentials'
  from lib/wiki_edits.rb:16:in `oauth_credentials_valid?'
  from lib/wiki_edits.rb:117:in `get_tokens'
  from json/common.rb:156:in `parse'
  from json/common.rb:156:in `parse'
```

**Comment by feelfreelinux** [comment]
Should i report whole exception via Raven, or just catch this specific case, and report nice message?
